### ISSUE TITLE
PW Generator doesn't appear in subpallet of member after first time checking `Allow login`

### ISSUE THREAD

**Issue by cliffparnitzky** [presprog/contao-password-suggestion#4]
When editing a member and first time checking the field `Allow login` the PW generator is not correctly extending the password widget (load the subpallet via ajax). After refreshing the browser, everything is fine.

**Comment by bezin** [comment]
Thanks for reporting. I already found the issue: styles and scripts are not loaded when a subpalette is lazy loaded. I will fix this as soon as I find a decent solution.

**Comment by cliffparnitzky** [comment]
Wow, "very big cinema" :wink: .  Thank you. I will check this asap.
